contact:
  email: powen@renci.org
  name: Phil Owen
  x-id: https://github.com/phillipsowen
  x-role: responsible developer
description: 'FASTAPI for Graph evaluation'
servers:
- description: Default server
  url: https://www.renci.org
title: Graph Database Evaluation via FASTAPI
